env = LANG,en_US.UTF-8
env = LC_ALL,en_US.UTF-8
#Took me hours to find this particular monitor resolution for my mac 
monitor=,2940x1846@75,auto,2.0


#to allow quick mouse driven window control:
input {
    kb_layout=us
    follow_mouse=1
    mouse_refocus=true

}

general {
    gaps_in=5
    gaps_out=10
    border_size=2
}

animations {
    enabled=yes
}
decoration {
    rounding = 12

    # Shadow settings to give it physical depth
    shadow {
        enabled = true
        range = 25                 # A larger range makes the shadow look bigger and thicker
        render_power = 4           # Makes the shadow drop-off sharper and more visible
        color = rgba(0, 0, 0, 0.6) # Deep, heavy black shadow to contrast the white transparency
    }

    blur {
        enabled = true
        size = 6           # Thicker blur for that frosted look
        passes =4          # Smoother gradients
        new_optimizations = true
        xray = false        # Keeps the blur consistent through windows
    }
}

#KeyBinds. They may look absurd because the command key is bound with SUPER by default and some combinations get overridden because it's probably a macos function that dominates.
bind=SUPER,Return,exec,foot
bind=SUPER,X,killactive
bind=SUPER,M,exit
bind=SUPER,D,exec,rofi -show drun
bind=SUPER,L,exec,hyprlock
bind = SUPER, F, exec, foot -e nvim
bind = SUPER, H, exec, /home/suryaansh/.config/hypr/scripts/wallpaper_loop.sh

#Switch workspaces: 
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = SUPER, S, togglespecialworkspace

# Move active window to a workspace with SUPER + SHIFT + [0-9] (again, SUPER+SHIFT+3, 4 or 5 does not work, macos native screen-capture functions take over)
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10
bind = SUPER SHIFT, S, movetoworkspace, special 

exec-once=wl-paste --type text --watch cliphist store
bind=SUPER,V,exec,cliphist list | rofi -dmenu | cliphist decode | wl-copy
#exec-once=hyprpaper
exec-once=mako

# 1. Fire up the wallpaper engine daemon
exec-once = swww-daemon

# 2. Let your loop script handle BOTH the initial login randomizer AND the 10-minute rotation
exec-once = sleep 1 && zsh /home/suryaansh/.config/hypr/scripts/wallpaper_loop.sh

exec-once = waybar
exec-once = playerctld daemon
exec-once = spice-vdagent

windowrule = match:class ^Rofi$, float on
windowrule = match:class ^Rofi$, no_shadow true
windowrule = match:class ^foot$, decorate true
